zk/src/org/zkoss/zk/ui/AbstractComponent.java, zk/src/org/zkoss/zk/ui/impl/MultiComposer.java, zk/src/org/zkoss/zk/ui/metainfo/Parser.java, zk/src/org/zkoss/zk/ui/sys/ComponentCtrl.java, zkbind/src/org/zkoss/bind/impl/BinderImpl.java, zktest/src/archive/bind/issue/parser/F80_Parser_MVVMAutoApply.zul, zktest/src/archive/bind/issue/parser/F80_Parser_StoreSubAnnotCnt.zul, zktest/src/org/zkoss/zktest/bind/issue/parser/F80_Parser_MVVMAutoApplyVM.java, zktest/src/org/zkoss/zktest/bind/issue/parser/F80_Parser_StoreSubAnnotCntComposer.java, zktest/src/org/zkoss/zktest/bind/issue/parser/F80_Parser_StoreSubAnnotCntVM.java, zktest/src/org/zkoss/zktest/zats/bind/issue/parser/F80_Parser_MVVMAutoApplyTest.java, zktest/src/org/zkoss/zktest/zats/bind/issue/parser/F80_Parser_StoreSubAnnotCntTest.java
1. If the attribute of viewModel being used, auto apply "BindComposer" ,and fix duplicate multiComposer
2. AbstractComponent support to count how many annotation in its subtree
=> ZK 8 Parser enhancement:

zk/src/org/zkoss/zk/ui/Page.java, zk/src/org/zkoss/zk/ui/impl/PageImpl.java, zk/src/org/zkoss/zk/ui/impl/UiEngineImpl.java, zk/src/org/zkoss/zk/ui/metainfo/PageDefinition.java, zk/src/org/zkoss/zk/ui/metainfo/Parser.java, zkdoc/release-note, zktest/src/archive/bind/issue/F02545ChildrenBindingSupportListModel_AttachDetach.zul
2. minor fix for test case zul
=> 1.Page scope template

zk/src/org/zkoss/zk/ui/AbstractComponent.java, zk/src/org/zkoss/zk/ui/sys/ComponentCtrl.java, zkbind/src/org/zkoss/bind/impl/BinderImpl.java, zkbind/src/org/zkoss/bind/sys/BinderCtrl.java, zkbind/src/org/zkoss/bind/tracker/impl/BindUiLifeCycle.java, zktest/src/archive/bind/parser/F80_Parser_StoreSubAnnotCnt.zul, zktest/src/org/zkoss/zktest/bind/parser/F80_Parser_StoreSubAnnotCntVM.java, zktest/src/org/zkoss/zktest/zats/bind/parser/F80_Parser_StoreSubAnnotCntTest.java
2.clear useless test case console output
3.add test case of StoreSubAnnotCntTest , check detach then attach
=> 1.refix mistake of check sub binding enhancement

zkbind/src/org/zkoss/bind/impl/BindComboitemRenderer.java, zkbind/src/org/zkoss/bind/impl/BindListitemRenderer.java, zkbind/src/org/zkoss/bind/impl/BindRadioRenderer.java, zkbind/src/org/zkoss/bind/impl/BindRowRenderer.java, zkbind/src/org/zkoss/bind/impl/BindTabboxRenderer.java, zkbind/src/org/zkoss/bind/impl/BindTreeitemRenderer.java, zkplus/src/org/zkoss/zkplus/databind/SelectedComboitemConverter.java, zul/src/org/zkoss/zul/Attributes.java, zul/src/org/zkoss/zul/Combobox.java, zul/src/org/zkoss/zul/Grid.java, zul/src/org/zkoss/zul/Listbox.java, zul/src/org/zkoss/zul/Radiogroup.java, zul/src/org/zkoss/zul/Tree.java, zul/src/org/zkoss/zul/impl/GridDataLoader.java, zul/src/org/zkoss/zul/impl/ListboxDataLoader.java
2. Replace "org.zkoss.zul.Combobox.onInitRender" with private static final String (Combobox)
=> 1. Replace "org.zkoss.zul.model.renderAs" with public static String

zk/src/archive/web/js/zk/au.js, zkdoc/release-note, zktest/src/archive/test2/B70-ZK-2818-1.zul, zktest/src/archive/test2/B70-ZK-2818.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B70_ZK_2818.java, zktest/src/org/zkoss/zktest/test2/B70_ZK_2818_1.java
2.ZK-2818: Busy message cannot be cleared under server push
=> 1.refix ZK-2687 : add zk.delayFunction in clearBusy & clearWrongValue

zktest/src/org/zkoss/zktest/test2/B80_ZK_2807_ViewModel.java
translate java 8 test case vm to java 5 compatible
=> refix Bug ZK_2807: notifyChange on method name only in ZK 8

zk/src/archive/web/js/zk/zk.js, zk/src/org/zkoss/zk/ui/AbstractComponent.java, zk/src/org/zkoss/zk/ui/sys/ConfigParser.java, zk/src/org/zkoss/zk/ui/sys/HtmlPageRenders.java, zk/src/org/zkoss/zk/ui/util/DataHandlerInfo.java, zkbind/src/org/zkoss/bind/converter/sys/DefaultJSONBindingParamConverter.java, zkbind/src/org/zkoss/bind/impl/BinderImpl.java
1.add setClientDataAttribute method
2.fix url encoding
3.add "links" tag
4.support client-side binding command mechanism
=> Enhance datahandler:

zk/src/archive/web/js/zk/widget.js, zk/src/archive/web/js/zk/zk.js, zk/src/org/zkoss/zk/ui/sys/ConfigParser.java, zk/src/org/zkoss/zk/ui/sys/HtmlPageRenders.java, zk/src/org/zkoss/zk/ui/util/Clients.java, zk/src/org/zkoss/zk/ui/util/DataHandlerInfo.java, zkbind/src/archive/web/js/zkbind/Binder.js
1. delete <depends>, change to <script>
2. <links> change to <link>
3. add a function trigger aftercommand in Clients.java
=> enhance ZK Datahandler:

zul/src/archive/web/zul/less/_zkmixins.less
1. removed unnecessary e() escape in less
2. re-ordered gradient declaration, moved svg to the front
=> refix removed unnecessary EL in css

zktest/src/archive/bind/issue/B01938GridListboxActivePage.zul, zktest/src/archive/test2/B80-ZK-1696-grid.zul, zktest/src/archive/test2/B80-ZK-1696-list.zul, zktest/src/org/zkoss/zktest/bind/issue/B01938GridListboxActivePage.java, zktest/src/org/zkoss/zktest/zats/test2/B80_ZK_1696_gridTest.java, zktest/src/org/zkoss/zktest/zats/test2/B80_ZK_1696_listTest.java, zul/src/org/zkoss/zul/AbstractListModel.java, zul/src/org/zkoss/zul/Grid.java, zul/src/org/zkoss/zul/Listbox.java, zul/src/org/zkoss/zul/PagingEventPublisher.java, zul/src/org/zkoss/zul/event/PagingListener.java
original fix for B80-ZK-1696 caused too much side effect, semi-reverting the fix and tries a new way of fixing the original bug, plus some spec re-confirm/change
also updated test cases to comply with the new/changed spec
=> refix B80-ZK-1696 with postEvent

zkdoc/release-note, zktest/src/archive/test2/B80-ZK-2919.zul, zktest/src/archive/test2/B80-ZK-2928.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B80_ZK_2919VM.java, zktest/src/org/zkoss/zktest/test2/B80_ZK_2928VM.java, zul/src/archive/web/js/zul/inp/Combobox.js, zul/src/archive/web/js/zul/inp/Comboitem.js, zul/src/org/zkoss/zul/Combobox.java
2. ZK-2919: WrongValueException prevents combobox from saving value
3. ZK-2928: Clear user input doesn't sent a onChange and onSelect
=> 1. refix ZK-1987

zkdoc/release-note, zktest/src/archive/test2/B70-ZK-2940.zul, zktest/src/archive/test2/B70-ZK-2941.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/menu/Menupopup.js, zul/src/archive/web/js/zul/wgt/Combobutton.js, zul/src/archive/web/js/zul/wgt/mold/combobutton.js
ZK-2941: Combobutton has not keyboard behavior
=> ZK-2940: Combobutton is not tab focusable if no tabIndex or tabindex="0"

zcommon/src/org/zkoss/lang/Library.java, zk/src/org/zkoss/zk/ui/metainfo/DefinitionLoaders.java, zk/src/org/zkoss/zk/ui/sys/ConfigParser.java, zkbind/src/archive/metainfo/zk/config.xml, zkbind/src/org/zkoss/bind/proxy/ProxyHelper.java, zkdoc/release-note, zktest/src/archive/test2/F80-ZK-3157.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/F80_ZK_3157_Composer.java, zktest/test/java/org/zkoss/zktest/zats/test2/F80_ZK_3157Test.java
=> ZK-3157: Library property support "name" - "values"

zkdoc/release-note, zktest/src/archive/test2/F80-ZK-3060.zul, zktest/src/archive/test2/F80-ZK-3234.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/F80_ZK_3060VM.java, zktest/test/java/org/zkoss/zktest/zats/test2/F80_ZK_3144Test.java, zul/src/archive/web/js/zul/mesh/Paging.js, zul/src/archive/web/js/zul/mesh/less/paging.less, zul/src/archive/web/js/zul/sel/SelectWidget.js, zul/src/org/zkoss/zul/Paging.java, zul/src/org/zkoss/zul/ext/Paginal.java, zul/src/org/zkoss/zul/ext/Paginated.java, zul/src/org/zkoss/zul/impl/MeshElement.java
Feature ZK-3060: Add a way to disabled paging in mold="paging" for grid
=> Feature ZK-3234: Add a disable attribute to paging component

zk/src/archive/metainfo/zk/config.xml, zk/src/archive/web/js/zk/flex.js, zk/src/archive/web/js/zk/widget.js, zk/src/archive/web/js/zk/zk.js, zk/src/org/zkoss/zk/ui/impl/AbstractUiFactory.java, zkdoc/release-note, zktest/src/archive/test2/F80-ZK-3255.zul, zktest/src/archive/test2/F80-ZK-3279.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/F80_ZK_3255Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/F80_ZK_3279Test.java, zul/src/archive/metainfo/xml/zul.xsd, zul/src/archive/metainfo/zk/lang.xml, zul/src/archive/web/js/zul/wgt/Idspace.js, zul/src/archive/web/js/zul/wgt/Nodom.js, zul/src/archive/web/js/zul/wgt/zk.wpd, zul/src/org/zkoss/zul/Idspace.java, zul/src/org/zkoss/zul/NoDOM.java
ZK-3279: Support a transparent component (no dom)
refine ZK-2955
=> ZK-3255: <Idspace> support no-dom widget

zktest/src/archive/test2/B70-ZK-2682.zul, zktest/src/archive/test2/F55-ZK-12.zul, zul/src/archive/web/js/zul/wgt/Checkbox.js
=> refix ZK-3519

zkdoc/release-note, zktest/src/archive/test2/B85-ZK-3643.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B85_ZK_3643Test.java, zul/src/archive/web/js/zul/mesh/HeadWidget.js, zul/src/archive/web/js/zul/mesh/HeaderWidget.js
http://tracker.zkoss.org/browse/ZK-3643
=> ZK-3643: JS error when resizing after adding column and invalidate

zkdoc/release-note, zktest/src/archive/test2/B85-ZK-3570.zul, zktest/src/archive/test2/config.properties, zul/src/org/zkoss/zul/Listbox.java
http://tracker.zkoss.org/browse/ZK-3570
=> ZK-3570: NPE when removing listmodel element

zkdoc/release-note, zktest/src/archive/test2/B85-ZK-3600.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/grid/Row.js, zul/src/archive/web/js/zul/sel/Listcell.js
http://tracker.zkoss.org/browse/ZK-3600
=> ZK-3600: Wrong size of grid scrollbar having first column invisible

zkdoc/release-note, zktest/src/archive/test2/F85-ZK-3681-Command.zul, zktest/src/archive/test2/F85-ZK-3681-Component.html, zktest/src/archive/test2/F85-ZK-3681-Component.zul, zktest/src/archive/test2/F85-ZK-3681-Databinding.zul, zktest/src/archive/test2/F85-ZK-3681-Jsvalidator.zul, zktest/src/archive/test2/F85-ZK-3681-Shadow.zul, zktest/src/archive/test2/F85-ZK-3681-Validator-Form.zul, zktest/src/archive/test2/F85-ZK-3681-Validator.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/F85_ZK_3681_Command_VM.java, zktest/src/org/zkoss/zktest/test2/F85_ZK_3681_Databinding_VM.java, zktest/src/org/zkoss/zktest/test2/F85_ZK_3681_Issue.java, zktest/src/org/zkoss/zktest/test2/F85_ZK_3681_Shadow_VM.java, zktest/src/org/zkoss/zktest/test2/F85_ZK_3681_Validator_VM.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_CommandTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_ComponentTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_DatabindingTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_JsvalidatorTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_ShadowTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_TestCase.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_ValidatorTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3681_Validator_FormTest.java
http://tracker.zkoss.org/browse/ZK-3681
=> ZK-3681: Add a new Fragment component

zkbind/src/org/zkoss/bind/validator/BeanValidator.java, zkdoc/release-note, zktest/src/archive/test2/F85-ZK-3684.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/F85_ZK_3684VM.java, zktest/test/java/org/zkoss/zktest/zats/test2/F85_ZK_3684Test.java
http://tracker.zkoss.org/browse/ZK-3684
=> ZK-3684: BeanValidator allows to set a self-defined message key

zkdoc/release-note, zktest/src/archive/test2/B85-ZK-3554.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B85_ZK_3554Test.java, zul/src/org/zkoss/zul/impl/XulElement.java
context, popup, and tooltip attribute support int value.
=> ZK-3554: Tooltip/Popup/Context ignoring usage errors

zkdoc/release-note, zktest/src/archive/test2/F85-ZK-3507.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/sel/ItemWidget.js, zul/src/archive/web/js/zul/sel/Listitem.js, zul/src/archive/web/js/zul/sel/SelectWidget.js, zul/src/archive/web/js/zul/sel/Treeitem.js
this feature will be applied on both listbox and tree
=> ZK-3507: Shift + up key can deselect listitems

zkdoc/release-note, zktest/src/archive/test2/B85-ZK-3717.zul, zktest/src/archive/test2/config.properties
=> ZK-3717: onBlur event missing on IOS Datebox

zk/src/archive/web/js/zk/widget.js, zul/src/archive/web/js/zul/Scrollbar.js, zul/src/archive/web/js/zul/box/Splitter.js, zul/src/archive/web/js/zul/db/Calendar.js, zul/src/archive/web/js/zul/db/Datebox.js, zul/src/archive/web/js/zul/db/mold/calendar.js, zul/src/archive/web/js/zul/dom.js, zul/src/archive/web/js/zul/inp/ComboWidget.js, zul/src/archive/web/js/zul/inp/Errorbox.js, zul/src/archive/web/js/zul/inp/InputWidget.js, zul/src/archive/web/js/zul/inp/Slider.js, zul/src/archive/web/js/zul/inp/mold/slider.js, zul/src/archive/web/js/zul/layout/East.js, zul/src/archive/web/js/zul/layout/LayoutRegion.js, zul/src/archive/web/js/zul/layout/North.js, zul/src/archive/web/js/zul/layout/South.js, zul/src/archive/web/js/zul/layout/West.js, zul/src/archive/web/js/zul/menu/Menu.js, zul/src/archive/web/js/zul/menu/Menubar.js, zul/src/archive/web/js/zul/menu/Menuitem.js, zul/src/archive/web/js/zul/mesh/Paging.js, zul/src/archive/web/js/zul/tab/Tabpanels.js, zul/src/archive/web/js/zul/tab/Tabs.js, zul/src/archive/web/js/zul/wgt/Caption.js, zul/src/archive/web/js/zul/wgt/Combobutton.js, zul/src/archive/web/js/zul/wgt/Toolbar.js, zul/src/archive/web/js/zul/wgt/mold/toolbar.js, zul/src/archive/web/js/zul/wnd/Panel.js, zul/src/archive/web/zul/html/messagebox.zul
=> ZK-3720: Provide a new theme as the default theme since ZK 8.5 (JS)

zk/src/archive/web/js/zk/dom.js, zul/src/archive/web/js/zul/WScroll.js, zul/src/archive/web/js/zul/db/Datebox.js, zul/src/archive/web/js/zul/menu/less/menu.less
offsetWidth returns non-rounding original value
WScroll button disable style when in head/tail position
Datebox drop button active style
Menu arrow style refined
=> refine ZK-3720: tablet issues

zkdoc/release-note, zktest/src/archive/test2/B85-ZK-3974.zul, zktest/src/archive/test2/config.properties
fixed in ebe2a9a2b1d15feae579acb58d2eb89c67f88dde
=> ZK-3974: spinner doesn't prevent users from violating its constraint

zkdoc/release-note, zktest/src/archive/test2/B86-ZK-3981.zul, zktest/src/archive/test2/B86-ZK-3983.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/box/Splitter.js
ZK-3983: a component doesn't resize correctly with a splitter in a vbox
=> ZK-3981: shrink a width with a splitter doesn't work

zk/src/archive/web/js/zk/dom.js, zkdoc/release-note, zktest/src/archive/test2/B86-ZK-4010.zul, zktest/src/archive/test2/B86-ZK-4011-tree.zul, zktest/src/archive/test2/B86-ZK-4011.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/grid/Row.js, zul/src/archive/web/js/zul/grid/less/grid.less, zul/src/archive/web/js/zul/mesh/FooterWidget.js, zul/src/archive/web/js/zul/mesh/Frozen.js, zul/src/archive/web/js/zul/mesh/HeaderWidget.js, zul/src/archive/web/js/zul/mesh/MeshWidget.js, zul/src/archive/web/js/zul/sel/Listcell.js, zul/src/archive/web/js/zul/sel/Treecell.js, zul/src/archive/web/js/zul/sel/less/listbox.less, zul/src/archive/web/js/zul/sel/less/tree.less, zul/src/archive/web/js/zul/wgt/Cell.js
ZK-4011: invisible columns are still visible in IE
=> ZK-4010: invisible listheaders are still visible in IE

zkdoc/release-note, zktest/src/archive/test2/B86-ZK-4053.zul, zktest/src/archive/test2/B86-ZK-4054.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4053Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4054Test.java, zul/src/org/zkoss/zul/Bandbox.java, zul/src/org/zkoss/zul/Combobox.java, zul/src/org/zkoss/zul/Combobutton.java
ZK-4054: setOpen() should not change open state of an invisible bandbox
=> ZK-4053: open a bandbox but isOpen() still returns false

zkdoc/release-note, zktest/src/archive/test2/F86-ZK-3138.zul, zktest/src/archive/test2/config.properties
ZK-4082: grid loading animation performance impact
=> refine ZK-3138: Data loading indicator for ROD

zkdoc/release-note, zktest/src/archive/test2/B86-ZK-4095.zul, zktest/src/archive/test2/config.properties, zul/src/archive/metainfo/xml/zul.xsd
=> ZK-4095: Add a false positive check threshold on the barcode scanner

zkdoc/release-note, zktest/src/archive/test2/B86-ZK-4100.zul, zktest/src/archive/test2/B86-ZK-4178.zul, zktest/src/archive/test2/F86-ZK-4023.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4100Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4178Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/F86_ZK_4023Test.java, zul/src/archive/web/js/zul/db/Datebox.js, zul/src/archive/web/js/zul/db/datefmt.js, zul/src/org/zkoss/zul/Datebox.java
ZK-4178: "Aug 32, 2018" became valid in lenient datebox after ZK-4023
=> ZK-4100: strictDate evaluated too early in ZK-4023

zktest/pom.xml, zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java, zktest/test/java/org/zkoss/zktest/zats/WebDriverTestCase.java, zktest/test/java/org/zkoss/zktest/zats/test2/B85_ZK_3761Test.java
=> Upgrade ChromiumHeadlessDriver dependencies versions (aligned with Puppeteer 1.11.0)

zel/src/org/zkoss/zel/ImportHandler.java, zkdoc/release-note, zktest/src/archive/test2/F86-ZK-4200.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/F86_ZK_4184VM.java, zktest/test/java/org/zkoss/zktest/zats/test2/F86_ZK_4200Test.java
Apply a patch from https://svn.apache.org/repos/asf/tomcat/trunk@1660133
=> ZK-4200: Improve ZEL ImportHandler performance

zktest/pom.xml, zktest/test/java/org/zkoss/zktest/zats/ChromiumFetcher.java, zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java
Upgrade to Chromium 74.0.3723.0 (r637110)
Upgrade to webdrivermanager 3.4.0
=> Upgrade to Chromium 74.0.3723.0 (r637110)

zk/src/archive/web/js/zk/uploadUtils.js, zk/src/org/zkoss/zk/au/http/AuDropUploader.java, zk/src/org/zkoss/zk/au/http/AuUploader.java, zk/src/org/zkoss/zk/ui/ext/Uploadable.java, zk/src/org/zkoss/zk/ui/ext/Uploads.java, zk/src/org/zkoss/zk/ui/impl/Attributes.java, zkdoc/release-note, zktest/src/archive/test2/B86-ZK-4220.zul, zktest/src/archive/test2/B86-ZK-4271.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4220Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4271Test.java, zul/src/archive/web/js/zul/Upload.js, zul/src/org/zkoss/zul/Button.java, zul/src/org/zkoss/zul/Menuitem.java
ZK-4220: UploadEvent.getMedia().getByteData() throws an unexpected exception when uploading
=> ZK-4271: native fileupload flag ignored for button/menuitem

zktest/src/archive/test2/B70-ZK-2784.zul, zktest/src/archive/test2/include/themes.zul
=> refine ZK-2784 test case

zktest/pom.xml, zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java, zktest/test/java/org/zkoss/zktest/zats/WebDriverTestCase.java, zktest/test/java/org/zkoss/zktest/zats/test2/B70_ZK_2729Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/F50_2940704_GridTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F50_2940704_ListboxTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F50_2940704_TreeTest.java, zktest/test/java/org/zkoss/zktest/zats/test2/F50_3052761Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/F86_ZK_4059Test.java
Upgrade to webdrivermanager 3.6.2
Fixed eval() returning nothing causes JavaScript circular exception
Add verbose log for debugging
=> Upgrade to Chromium 77.0.3835.0

zkdoc/release-note, zktest/src/archive/test2/F90-ZK-3769.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/F90_ZK_3769Test.java, zul/src/archive/metainfo/xml/zul.xsd, zul/src/archive/web/js/zul/db/Datebox.js, zul/src/org/zkoss/zul/Datebox.java
=> ZK-3769: Specify a default time for Datebox

zkbind/src/org/zkoss/bind/converter/sys/FormattedTemporalConverter.java, zkbind/src/org/zkoss/bind/impl/SystemConverters.java, zkdoc/release-note, zktest/src/archive/test2/F90-ZK-4352.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/F90_ZK_4352VM.java, zktest/test/java/org/zkoss/zktest/zats/test2/F90_ZK_4352Test.java
=> ZK-4352: provide a built-in date format converter that accepts LocalDate

gulpfile.js, package-lock.json, package.json
=> Fix babel.config.js root

zkdoc/release-note, zktest/src/archive/test2/F90-ZK-4373.zul, zktest/src/archive/test2/F90-ZK-4374.zul, zktest/src/archive/test2/config.properties, zul/src/archive/metainfo/xml/zul.xsd, zul/src/archive/web/zul/less/_zkvariables.less
ZK-4374: Provide a multislider component
=> ZK-4373: Provide a rangeslider component

bin/zklessChecker, package-lock.json, zktest/src/archive/WEB-INF/zk.xml, zul/pom.xml
remove "npm ci"
turn WCS cache off for zktest
=> refine maven frontend-maven-plugin build destination error

zktest/src/archive/test2/B90-ZK-4402.zul, zktest/src/archive/test2/B90-ZK-4403.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B90_ZK_4402Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B90_ZK_4403Test.java
ZK-4403: Stepbar insert Step - broken broken layout
=> ZK-4402: Stepbar UIException using default renderer

zk/src/archive/web/js/zk/flex.js, zk/src/archive/web/js/zk/widget.js, zul/src/archive/web/js/zul/mesh/HeaderWidget.js
remove ie support
fix margin issue
=> refine ZK-317

zk/src/archive/web/js/zk/flex.js, zktest/src/archive/test2/B90-ZK-4411.zul, zktest/src/archive/test2/B90-ZK-4412.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B90_ZK_4411Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B90_ZK_4412Test.java, zul/src/archive/web/js/zul/box/less/layout.less, zul/src/archive/web/zul/less/norm.less
ZK-4412: css flex: hlayout valign has no effect
=> ZK-4411: css flex doesn't size buttons

zktest/src/archive/test2/B90-ZK-4426.zul, zktest/src/archive/test2/B90-ZK-4430.zul, zktest/src/archive/test2/B90-ZK-4431.zul, zktest/src/archive/test2/config.properties
ZK-4427: Multislider non-nested ranges
ZK-4428: Avoid rangeslider mark resize-reposition-delay
ZK-4430: onRangeValueChange event fired to every rangeslider component
ZK-4431: multislider event doesn't fire
=> ZK-4426: Multislider push handles failing to update

zk/src/archive/web/js/zk/drag.js
ZK-4424: range slider dragging issue
=> Refine ZK-4373, ZK-4374

zktest/src/archive/test2/B90-ZK-4427.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B90_ZK_4427Test.java
ZK-4427: Multislider non-nested ranges
=> refine ZK-4373, ZK-4374, ZK-4426

zkdoc/release-note, zktest/src/archive/test2/B90-ZK-4471.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/wnd/less/window.less
=> ZK-4471: The line-break of message in Messagebox is wrong in IE

zktest/pom.xml, zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java, zktest/test/java/org/zkoss/zktest/zats/DockerChromeRemoteWebDriver.java, zktest/test/java/org/zkoss/zktest/zats/WebDriverTestCase.java
Add RemoteWebDriverHasTouchScreen to solve $LANG issue on Linux
Upgrade webdrivermanager to 3.8.1
=> Upgrade Chromium to 80.0.3987.106

zcommon/pom.xml, zel/pom.xml, zhtml/pom.xml, zk/pom.xml, zkbind/pom.xml, zkplus-legacy/pom.xml, zkplus/pom.xml, zksandbox/pom.xml, zktest/pom.xml, zkwebfragment/pom.xml, zul/pom.xml, zweb-dsp/pom.xml, zweb/pom.xml
Update frontend-maven-plugin version
=> Refine POM (https, UTF-8 encoding)

zk/src/archive/web/js/zk/widget.js, zk/src/org/zkoss/zk/ui/sys/HtmlPageRenders.java, zktest/test/java/org/zkoss/zktest/zats/test2/F80_ZK_2613Test.java
refine ZK-4564, resourceURI in embedded ZK
=> refine ZK-2613 test case

zktest/src/archive/wcag/menubar.zul
- Menuitem toggles checked if autocheck enabled
- Menu opens menupopup
- Menuitem activates
=> refine ZK-4598: Spacekey support

package-lock.json, package.json, zk-parent/pom.xml
Update zkless-engine to 1.1.5
Update browser-sync to 2.26.12
=> Add skip switches for NpmInstall and Zklessc

zul/src/archive/web/js/zul/wgt/less/toolbar.less, zul/src/archive/web/zul/less/_zkvariables.less
focus: inset 3px
Organigram uses variables
=> refine ZK-4598: WCAG Palettes

zktest/test/java/org/zkoss/zktest/zats/wcag/TabboxTest.java
When a tab gets selected, focus it
=> refine ZK-4598: tablist adds aria-orientation

zk/src/archive/web/js/zk/effect.js, zktest/src/archive/test2/F95-ZK-4624-focus.zul, zktest/src/org/zkoss/zktest/test2/F95_ZK_4624FocusVM.java, zktest/test/java/org/zkoss/zktest/zats/test2/F95_ZK_4624Test.java
refine ZK-4624, adjust test case
=> refine ZK-4598, remove misused aria-hidden in shadow

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4610.zul, zktest/src/archive/test2/B95-ZK-4632.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B95_ZK_4610VM.java, zktest/src/org/zkoss/zktest/test2/B95_ZK_4632VM.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4610Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4632Test.java, zul/src/archive/web/js/zul/sel/Listbox.js, zul/src/archive/web/js/zul/sel/mold/listbox.js
ZK-4610: Listbox Partial invalidate breaks popup ROD
=> ZK-4632: Re-rendering a listbox produces a javascript error

zktest/src/archive/wcag/window.zul, zktest/test/java/org/zkoss/zktest/zats/wcag/WindowTest.java
Add Escape keydown handling
Add default aria-labelledby if none is provided
=> refine ZK-4598: Window adds role=dialog and aria-modal if mode=modal

zktest/pom.xml, zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java
Upgrade webdrivermanager to 4.2.0
=> Upgrade Chromium to 85.0.4182.0

zul/src/archive/web/js/zul/sel/less/listbox.less, zul/src/archive/web/js/zul/wgt/less/toolbar.less, zul/src/archive/web/zul/less/profiles/_compact.less
fix the height of listheader buttons in compact profile
=> refine ZK-4560: toolbarbutton apply min-height workaround

zktest/src/archive/test2/B30-1997828.zul, zktest/src/archive/test2/B30-2562880.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B30_1997828Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B30_2562880Test.java
Convert B30_1997828Test, B30_2562880Test into ZATS
=> refine B30-1997828.zul popup width, B30-2562880.zul sort icon

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4644.zul, zktest/src/archive/test2/B95-ZK-4645.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B95_ZK_4644Composer.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4644Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4645Test.java
ZK-4645: Stepbar Error - render dynamically with model
=> ZK-4644: Rendering Stepbar dynamically causes error

.github/workflows/zk-build.yml
=> Build script using Github Action

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4713.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4713Test.java, zul/src/archive/web/js/zul/mesh/MeshWidget.js
ZK-4713: listbox flickers with autopaging in a specific height
=> ZK-4713: listbox flickers with autopaging in a specific height

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4505.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4505Test.java, zul/src/archive/web/js/zul/wgt/Groupbox.js
ZK-4505: resize() doesn't reduce a groupbox height with title
=> ZK-4505: resize() doesn't reduce a groupbox height with title

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-3316.zul, zktest/src/archive/test2/B95-ZK-3317.zul, zktest/src/archive/test2/B95-ZK-3318.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3316Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3317Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3318Test.java, zul/src/archive/web/js/zul/mesh/MeshWidget.js
ZK-3317:Listbox with hflex="min" produces a horizontal scrollbar
=> ZK-3317:Listbox with hflex="min" produces a horizontal scrollbar

zktest/src/archive/test2/B95-ZK-3316.zul, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3316Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3317Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3318Test.java, zul/src/archive/web/js/zul/mesh/MeshWidget.js
refine ZK-3317: Listbox with hflex="min" produces a horizontal scrollbar
=> refine ZK-3317: Listbox with hflex="min" produces a horizontal scrollbar

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4084.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4084Test.java, zul/src/archive/web/js/zul/mesh/MeshWidget.js
zk-4084: New added header is invisible when all headers have fixed width
=> ZK-4084: New added header is invisible when all headers have fixed width

zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3316Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3317Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_3318Test.java
refine ZK-3317-2: Listbox with hflex="min" produces a horizontal scrollbar
=> refine ZK-3317-2: Listbox with hflex="min" produces a horizontal scrollbar

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4746.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4746Test.java, zul/src/org/zkoss/zul/Selectbox.java
ZK-4746: Selectbox component doesn't implement Disable interface
=> ZK-4746: Selectbox component doesn't implement Disable interface

zk/src/archive/web/js/zk/au.js, zkdoc/release-note, zktest/src/archive/WEB-INF/zk.xml, zktest/src/archive/test2/B95-ZK-4742-login.zul, zktest/src/archive/test2/B95-ZK-4742-zk.xml, zktest/src/archive/test2/B95-ZK-4742.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4742Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4742_1Test.java
ZK-4742: client side http error handling not reachable
=> ZK-4742: client side http error handling not reachable

zk/src/archive/web/js/zk/zk.js, zktest/pom.xml, zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java
Upgrade to Chromium 88.0.4298.0
forkCount can be set by -DforkCount
=> refine zktest: enable zk_log textarea in mobile

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4619.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4619Test.java, zul/src/org/zkoss/zul/Radio.java
ZK-4619: The radiogroup of cloned radio is not updated
=> ZK-4619: The radiogroup of cloned radio is not updated

zk/src/archive/web/js/zk/flex.js, zk/src/archive/web/js/zk/mount.js, zk/src/archive/web/js/zk/utl.js, zk/src/archive/web/js/zk/widget.js, zktest/src/archive/test2/B86-ZK-4154.zul, zul/src/archive/web/js/zul/box/Hlayout.js, zul/src/archive/web/js/zul/box/Splitter.js
Fix reflow from zUtl.fireSized
=> refine ZK-4154: rename to _preBeforeSizeReadOnly

zul/src/archive/web/js/zul/wgt/Groupbox.js
refine ZK-4505: resize() doesn't reduce a groupbox height with title
=> refine ZK-4505: resize() doesn't reduce a groupbox height with title

zktest/src/archive/test2/B80-ZK-3207.zul
refine test case ZK-3207: test old flex
=> refine test case ZK-3207: test old flex

zk/src/archive/web/js/zk/domsafari.js, zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4322.zul, zktest/src/archive/test2/config.properties
ZK-4322: Listbox position is wrong after calling setSelectied in Safari
=> ZK-4322: Listbox position is wrong after calling setSelectied in Safari

zkdoc/release-note, zktest/src/archive/test2/B95-ZK-4760.zul, zktest/src/archive/test2/config.properties, zul/src/archive/web/js/zul/dom.js, zul/src/archive/web/js/zul/wnd/less/window.less, zul/src/archive/web/js/zul/wnd/messagebox.js, zul/src/archive/web/zul/html/messagebox.zul, zul/src/archive/web/zul/less/_zkvariables.less, zul/src/archive/web/zul/less/profiles/_compact.less
ZK-4760: default error message box hard coded width (too small)
=> ZK-4760: default error message box hard coded width (too small)

zkdoc/release-note, zktest/src/archive/test2/F96-ZK-4330.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4330Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4330_2Test.java, zul/src/archive/web/js/zul/sel/Tree.js, zul/src/archive/web/js/zul/sel/Treecol.js, zul/src/archive/web/js/zul/sel/Treeitem.js, zul/src/archive/web/js/zul/sel/less/tree.less, zul/src/org/zkoss/zul/Tree.java
ZK-4330: provide select-all checkbox in tree component
=> ZK-4330: provide select-all checkbox in tree component

zk/src/archive/web/js/zk/au.js, zk/src/archive/web/js/zk/utl.js, zkdoc/release-note, zktest/src/archive/WEB-INF/zk.xml, zktest/src/archive/test2/F96-4524-zk.xml, zktest/src/archive/test2/F96-ZK-4524.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4524Test.java
ZK-4524: blocking all user keyboard input during processing message showing
=> ZK-4524: blocking all user keyboard input during processing message showing

zul/src/archive/web/js/zul/sel/Treecol.js, zul/src/org/zkoss/zul/Tree.java
=> refine Treecol doClick

zkdoc/release-note
=> refine release-note

zkdoc/release-note, zktest/src/archive/test2/F96-ZK-4631.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4631Test.java, zul/src/archive/metainfo/xml/zul.xsd, zul/src/archive/web/js/zul/wgt/Toolbar.js, zul/src/archive/web/js/zul/wgt/mold/toolbar.js, zul/src/org/zkoss/zul/Toolbar.java
ZK-4631: Add option to choose toolbar overflow icon
=> ZK-4631: Add option to choose toolbar overflow icon

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4597.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4597Test.java, zul/src/archive/web/js/zul/wgt/Combobutton.js, zul/src/archive/web/js/zul/wgt/mold/combobutton.js
ZK-4597: Disabled Combobutton should not be able to focus or controlled by keyboard
=> ZK-4597: Disabled Combobutton should not be able to focus or controlled by keyboard

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4808.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4808Test.java, zul/src/archive/web/js/zul/menu/Menu.js
ZK-4808: menu click listener ignored (unexpectedly)
=> ZK-4808: menu click listener ignored (unexpectedly)

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4636.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4636Test.java, zul/src/archive/web/js/zul/inp/Slider.js
ZK-4636: Slider curpos might be larger then maxpos while dragging
=> ZK-4636: Slider curpos might be larger then maxpos while dragging

zktest/src/archive/test2/config.properties
=> refine ZK-4808

zkdoc/release-note, zktest/src/archive/test2/F96-ZK-4783.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4783Test.java, zul/src/archive/web/js/zul/dom.js, zul/src/archive/web/js/zul/wnd/less/window.less, zul/src/archive/web/js/zul/wnd/messagebox.js, zul/src/archive/web/zul/html/messagebox.zul, zul/src/archive/web/zul/less/_zkvariables.less, zul/src/archive/web/zul/less/profiles/_compact.less
ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)
=> ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4700.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4700Test.java
ZK-4700: chosenbox inplace influence other chosenbox
=> ZK-4700: chosenbox inplace influence other chosenbox

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4819.zul, zktest/src/archive/test2/B96-ZK-4820.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4820Test.java
ZK-4820: Chosenbox aria-activedescendant out of sync (za11y.jar)
=> ZK-4819: Chosenbox performance (with za11y.jar)

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4792.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4792Test.java
ZK-4792: Chosenbox getSelectedIndex() return wrong index with ListModelList
=> ZK-4792: Chosenbox getSelectedIndex() return wrong index with ListModelList

zk/src/archive/web/WEB-INF/tld/zk/core.dsp.tld, zk/src/org/zkoss/zk/fn/ZkFns.java, zkdoc/release-note, zul/src/archive/web/zul/less/norm.less
ZK-4828: remove externally loaded resources with internal refs.
=> ZK-4828: remove externally loaded resources with internal refs.

zk/src/archive/web/js/zk/domtouch.js
https://github.com/DevExpress/testcafe/issues/6114
=> refine ZK-4835: In TestCafe, event.sourceCapabilities is null

zul/src/archive/web/js/zul/grid/Grid.js, zul/src/archive/web/js/zul/mesh/MeshWidget.js, zul/src/archive/web/js/zul/sel/Listbox.js
https://stackoverflow.com/a/30506051
=> refine ZK-4890: Use Promise

zk/src/archive/web/js/zk/uploadUtils.ts, zk/src/org/zkoss/zk/ui/http/ExecutionImpl.java, zk/src/org/zkoss/zk/ui/sys/HtmlPageRenders.java, zkdoc/release-note, zkplus/src/org/zkoss/zkplus/embed/Renders.java, zktest/src/archive/test2/B96-ZK-4922.zul, zktest/src/archive/test2/B96-ZK-4922test.html, zktest/src/archive/test2/B96-ZK-4923-1.zul, zktest/src/archive/test2/B96-ZK-4923-1test.html, zktest/src/archive/test2/B96-ZK-4923.zul, zktest/src/archive/test2/B96-ZK-4923test.html, zktest/src/archive/test2/config.properties, zweb/src/org/zkoss/web/servlet/Servlets.java, zweb/src/org/zkoss/web/servlet/http/Encodes.java
ZK-4923: zEmbedded download fails
=> ZK-4922: zEmbedded upload fails

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4781.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4781Test.java
=> ZK-4781: No error message appreared in invalid Longbox in mobile

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4543.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4543Test.java, zul/src/archive/web/js/zul/db/Calendar.js
ZK-4543: Calendar should respect the constraint while Month changing
=> ZK-4543: Calendar should respect the constraint while Month changing

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4788.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4788Test.java, zul/src/archive/web/js/zul/inp/InputWidget.js, zul/src/org/zkoss/zul/impl/InputElement.java
ZK-4788: unset default value for InputElement
=> ZK-4788: setCols(0) causes exception for InputElement

build.target.xml, zk/src/org/zkoss/zk/ui/http/Wpds.java, zk/src/org/zkoss/zk/ui/impl/DesktopImpl.java, zul/src/org/zkoss/zul/Datebox.java, zul/src/org/zkoss/zul/Doublebox.java, zul/src/org/zkoss/zul/Listbox.java
Fix https://github.com/checkstyle/checkstyle/issues/8018
=> Update Checkstyle to 8.44

zktest/src/archive/test2/F96-ZK-4777.zul
refine ZK-4777: setBackgroundColor(null) should be white
=> refine ZK-4777: setBackgroundColor(null) should be white

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-4868.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4868Test.java
ZK-4868: signature background color should be white while setBackgroundColor(null)
=> ZK-4868: signature background color should be white while setBackgroundColor(null)

zul/src/archive/web/js/zul/wnd/less/window.less, zul/src/archive/web/zul/html/messagebox.zul
refine ZK-4783: ie grow a scroll bar unexpectedly
=> refine ZK-4783: ie grow a scroll bar unexpectedly

zktest/src/archive/test2/B96-ZK-4748.zul, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4748Test.java, zul/src/archive/web/js/zul/inp/Bandpopup.js
refine ZK-4748: Bandpopup close while open the treeitem
=> refine ZK-4748: Bandpopup close while open the treeitem

zul/src/archive/metainfo/xml/zul.xsd
Add ckeditor attributes to zul.xsd
=> Add ckeditor attributes to zul.xsd

zul/src/archive/metainfo/xml/zul.xsd
=> refine zul.xsd version number

zkdoc/release-note, zktest/src/main/webapp/test2/B100-ZK-5138.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B100_ZK_5138Test.java, zul/src/main/resources/web/js/zul/grid/Row.js
ZK-5138: Grid row setAlign not work after rendered
=> ZK-5138: Grid row setAlign not work after rendered

zkdoc/release-note, zktest/src/main/webapp/test2/B100-ZK-5120.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B100_ZK_5120Test.java, zul/src/main/java/org/zkoss/zul/Combobox.java, zul/src/main/resources/web/js/zul/inp/Combobox.js, zul/src/main/resources/web/js/zul/inp/less/combo.less
ZK-5120: Combobox smart update emptySearchMessage doesn't work
=> ZK-5120: Combobox smart update emptySearchMessage doesn't work

zk/src/main/resources/web/js/zk/widget.ts, zul/src/main/resources/web/js/zul/global.d.ts, zul/src/main/resources/web/js/zul/mesh/ColumnMenuWidget.ts, zul/src/main/resources/web/js/zul/tab/Tab.ts, zul/src/main/resources/web/js/zul/tab/Tabbox.ts, zul/src/main/resources/web/js/zul/tab/Tabpanel.ts, zul/src/main/resources/web/js/zul/tab/Tabpanels.ts, zul/src/main/resources/web/js/zul/tab/Tabs.ts, zul/src/main/resources/web/js/zul/tab/index.ts, zul/src/main/resources/web/js/zul/tab/zk.wpd
1. Define _onUngroup in ColumnMenuWidget as method (incorporate upstream)
2. Resolve F61-ZK-970.zul with TabboxSkipper
=> Migrate zul/tab to TS

tsconfig.json, zk/src/main/resources/web/js/zk/au.ts, zk/src/main/resources/web/js/zk/dom.ts, zk/src/main/resources/web/js/zk/drag.ts, zk/src/main/resources/web/js/zk/evt.ts, zk/src/main/resources/web/js/zk/widget.ts, zk/tsconfig.json, zul/src/main/resources/web/js/zul/grid/Grid.ts, zul/src/main/resources/web/js/zul/inp/Combobox.ts, zul/src/main/resources/web/js/zul/menu/Menu.ts, zul/src/main/resources/web/js/zul/sel/Listbox.ts
This accompanies the "Migrate zkex to TS" PR in zkoss/zkcml.
=> Migrate zkex to TS

zk/src/archive/web/js/zk/dom.ts, zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5159.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5159Test.java
=> ZK-5159: Firefox Windows 11 scrollbar doesn't have height, cause missing scrollbar

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5240.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B96_ZK_5240Composer.java
This PR should be merged alongside https://github.com/zkoss/zkcml/pull/968
=> ZK-5240: calculation issue in tpad cause grid to render entire content at once

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5111.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5111Test.java
refers to - https://github.com/zkoss/zkcml/pull/969
=> ZK-5111: require.js causes Toast.show() failed

zhtml/src/main/java/org/zkoss/zhtml/impl/AbstractTag.java, zk/src/main/java/org/zkoss/zk/ui/HtmlNativeComponent.java, zk/src/main/resources/web/js/zk/widget.ts, zkdoc/release-note, zktest/src/main/webapp/test2/B60-ZK-745.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B60_ZK_745Test.java
this PR alongside this commit - https://github.com/zkoss/zkcml/pull/979
=> ZK-5270: Adjust ID generation mechanism in ZHTML Component

zkbind/src/main/java/org/zkoss/bind/impl/ParamCall.java
PR alongside this https://github.com/zkoss/zkcml/pull/980
=> ZK-5267: Client MVVM: ForEach support map iteration

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5251.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5251Test.java
This PR should be merge alongside https://github.com/zkoss/zkcml/pull/987.
=> ZK-5251: listbox select mold produces js error in a mobile browser

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5399.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B96_ZK_5399VM.java
This PR should be merge alongside https://github.com/zkoss/zkcml/pull/990.
=> ZK-5399: Number of NoDOM increases unexpectedly 

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5133.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5133Test.java, zul/src/org/zkoss/zul/Radio.java
=> ZK-5133: Radio onPageAttached condition causes onPageAttach to not fi… 

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5429.zul, zktest/src/archive/test2/B96-ZK-5433.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5429Test.java, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5433Test.java, zul/src/archive/web/js/zul/tab/Tabs.js
ZK-5433: tabbox doesn't scroll the selected tab into the current view when shrinking its width
=> ZK-5429: tabbox scroll unsynced when resizing with toolbar

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5432.zul, zktest/src/archive/test2/config.properties
This PR should be merge alongside zkoss/zkcml#996
=> ZK-5432: aria-activedescendant is generated at wrong place 

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5076.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B96_ZK_5076Composer.java, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5076Test.java, zul/src/archive/web/js/zul/sel/Option.js, zul/src/archive/web/js/zul/sel/Select.js
=> ZK-5076: Listbox in select mold setModel + set selectedIndex causes u… 

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5379.zul, zktest/src/archive/test2/config.properties, zktest/src/org/zkoss/zktest/test2/B96_ZK_5379Composer.java, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5379Test.java
This PR should be merged alongside [zkcml#997](https://github.com/zkoss/zkcml/pull/997).
=> ZK-5379: Floating scrollbar prevent anchornav from scrolling

zk/classpath, zk/pom.xml, zk/src/org/zkoss/zk/ui/http/SourceMapManager.java, zktest/pom.xml, zktest/war.libs.all
add jar name in config for zktest deployment
This PR should be merge alongside zkoss/zkcml#999
=> Refine ZK-4194, upgrade closure-compiler to v20220601

zkdoc/release-note
…ichlet, this commit is alongside with https://github.com/zkoss/zkcml/pull/1021
=> ZK-5422: Provide some utile APIs to update IComponent Tree

zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1019.
=> ZK-5494: Background and foreground colors do not have a sufficient contrast ratio

zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1018.
=> ZK-5481: The checkbox in a listitem doesn't have a role "checkbox"

zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1033.
=> ZK-5498: Some checkboxes do not have [aria-checked] attribute, and they do not have accessible names

build.gradle
This PR should be merge alongside zkoss/zkcml#1042
=> refine genprop gradle script

zkdoc/release-note, zktest/src/main/webapp/test2/F100-ZK-5213.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5213Test.java
This PR should be merge alongside zkoss/zkcml#1022.
=> ZK-5213: Improve accessibility by add tooltips on icons

zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/F100_ZK_5503_Composer.java, zktest/src/main/webapp/test2/F100-ZK-5502.zul, zktest/src/main/webapp/test2/F100-ZK-5503.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5502Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5503Test.java, zul/src/main/java/org/zkoss/zul/impl/LabelImageElement.java, zul/src/main/resources/metainfo/xml/zul.xsd, zul/src/main/resources/web/js/zul/LabelImageWidget.ts
This PR should be merge alongside zkoss/zkcml#1043.
=> ZK-5502: Allow users to customize tooltip on the icon, ZK-5503: Allow users to set multiple icons and tooltips on the same LabelImageElement

zkdoc/release-note
This should be merged alongside https://github.com/zkoss/zkcml/pull/1049
=> ZK-5469: Make cloudMode true by default for ZK Stateless

zktest/build.gradle, zktest/gradle.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4194Test.java
This must be merged alongside https://github.com/zkoss/zkcml/pull/1050
=> Upgrade test dependencies and fix chrome-driver 115+ issue

zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/F100_ZK_5503_Composer.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5213Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5503Test.java, zul/src/main/resources/web/js/zul/LabelImageWidget.ts
This PR should be merge alongside zkoss/zkcml#1052.
=> refix ZK-5213, ZK-5503, ZK-3636, add upgrade notes of ZK-5503.

zkdoc/release-note, zktest/src/main/webapp/test2/F100-ZK-5408-1-zk.xml, zktest/src/test/java/org/zkoss/zktest/zats/bind/basic/ModulizeTest.java, zktest/src/test/java/org/zkoss/zktest/zats/bind/comp/MenuitemTest.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/B50_3363687Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/B86_ZK_4053Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5408Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5408_1Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F90_ZK_4347_constTest.java
This PR should be merge alongside zkoss/zkcml#1059.
=> ZK-5408: Enable InaccessibleWidgetBlockService by default

javadoc.gradle
This should be merged alongside https://github.com/zkoss/zkcml/pull/1072.
=> refine javadoc build script

zk/src/main/java/org/zkoss/zk/ui/metainfo/Parser.java, zkbind/src/main/java/org/zkoss/bind/impl/ParamCall.java, zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/F100_ZK_5018SyntaxVM.java, zktest/src/main/webapp/test2/F100-ZK-5018-command.zul, zktest/src/main/webapp/test2/F100-ZK-5018-syntax-exception.zul, zktest/src/main/webapp/test2/F95-ZK-4552-nested.zul, zktest/src/main/webapp/test2/F95-ZK-4552-syntax-exception.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5018Test.java
refine ZK-4552 test cases (after ZK-5018)
This PR should be merge alongside zkoss/zkcml#1102
=> ZK-5018: Enhance simplified MVVM syntax

zk/src/main/resources/web/js/zk/widget.ts, zkdoc/release-note, zktest/src/main/webapp/test2/B100-ZK-5593.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B100_ZK_5593Test.java, zul/src/main/resources/web/js/zul/sel/Listbox.ts, zul/src/main/resources/web/js/zul/sel/mold/listbox.js
This should be merged alongside zkoss/zkcml#1106.
=> ZK-5593: inputWidget bind_ accesses input dom node may not exist

zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/F100_ZK_4988VM.java, zktest/src/main/webapp/test2/F100-ZK-4988.html, zktest/src/main/webapp/test2/F100-ZK-4988.zul, zktest/src/main/webapp/test2/config.properties
This should be merged alongside zkoss/zkcml#1114.
=> ZK-4988: zEmbedded support for websocket

zkdoc/release-note, zktest/build.gradle, zktest/src/main/webapp/wcag/tabbox.zul
This PR should be merge alongside zkoss/zkcml#1119.
=> ZK-5527: Upgrade WCAG with the lighthouse 11.x detection tools

zkbind/src/main/java/org/zkoss/bind/impl/ChildrenBindingListModelDataEvent.java, zul/src/main/java/org/zkoss/zul/event/ListDataEvent.java
This PR should be merge alongside zkoss/zkcml#1122
=> fix for sonarQube, Serializable issue

zkdoc/release-note, zktest/src/main/webapp/test2/F100-ZK-3853-1.zul, zktest/src/main/webapp/test2/F100-ZK-3853-2.zul, zktest/src/main/webapp/test2/F100-ZK-3853-3.zul, zktest/src/main/webapp/test2/F100-ZK-3853-4.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_3853_1Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_3853_2Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_3853_3Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_3853_4Test.java, zul/src/main/java/org/zkoss/zul/Tree.java, zul/src/main/java/org/zkoss/zul/event/TreeDataEvent.java, zul/src/main/java/org/zkoss/zul/ext/TristateModel.java, zul/src/main/resources/web/js/zul/sel/less/tree.less
The PR should be merged alongside https://github.com/zkoss/zkcml/pull/1123
=> ZK-3853: Tree supports 3-states selection model

zkdoc/release-note, zktest/src/archive/test2/B96-ZK-5453.zul, zktest/src/archive/test2/config.properties, zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5453Test.java
This PR should be merge alongside zkoss/zkcml#1126.
=> ZK-5453: XSS in chosenbox

zktest/src/main/webapp/test2/B36-2813877.zul, zktest/src/main/webapp/test2/B50-ZK-631.zul
1. after removing deprecated menu/menuitem setSrc
2. sync ZUL for ZTL test
=> refine test cases

zktest/src/test/java/org/zkoss/zktest/zats/test2/Z30_echoEventTest.java
This PR should be merge alongside zkoss/ztltest#392.
=> Move Z30-echoEvent from ztl to zktest

zk/src/main/java/org/zkoss/zk/ui/Impls.java, zk/src/main/java/org/zkoss/zk/ui/impl/AbstractWebApp.java, zk/src/main/resources/web/js/zk/zuml/Parser.ts, zkbind/src/main/java/org/zkoss/bind/proxy/ListModelArrayProxy.java, zkplus/src/main/java/org/zkoss/zkplus/jpa/OpenEntityManagerInViewListener.java, zkplus/src/main/java/org/zkoss/zkplus/util/ThreadLocalListener.java, zul/src/main/java/org/zkoss/zul/Captcha.java, zul/src/main/java/org/zkoss/zul/theme/CookieThemeResolver.java, zul/src/main/resources/web/js/zul/db/datefmt.ts, zul/src/main/resources/web/js/zul/inp/SimpleConstraint.ts, zweb/src/main/java/org/zkoss/web/servlet/Servlets.java
This PR should be merge alongside zkoss/zkcml#1153.
=> Fix sonarqube security issues

zk/src/main/java/org/zkoss/zk/au/http/AuMultipartUploader.java, zkdoc/release-note
Tested by `B100_ZK_5393Test.java`.
=> ZK-5775: Improve ZK-5393 by caching FileUpload classes

zkbind/src/main/java/org/zkoss/bind/impl/BinderImpl.java, zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/B101_ZK_5756_Page_A_VM.java, zktest/src/main/java/org/zkoss/zktest/test2/B101_ZK_5756_Page_B_VM.java, zktest/src/main/webapp/test2/B101-ZK-5756-a.zul, zktest/src/main/webapp/test2/B101-ZK-5756-b.zul, zktest/src/main/webapp/test2/B101-ZK-5756.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B101_ZK_5756Test.java
This should be merged alongside https://github.com/zkoss/zkcml/pull/1170
=> ZK-5756: a MatchMedia request causes java.lang.IllegalArgumentException

zk/src/main/java/org/zkoss/zk/ui/AbstractComponent.java, zk/src/main/java/org/zkoss/zk/ui/impl/UiEngineImpl.java, zk/src/main/java/org/zkoss/zk/ui/impl/UiVisualizer.java, zk/src/main/java/org/zkoss/zk/ui/sys/ComponentCtrl.java, zk/src/main/java/org/zkoss/zk/ui/sys/Visualizer.java, zkdoc/release-note, zktest/src/main/webapp/test2/B101-ZK-5792.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B101_ZK_5792Test.java
This should be merged alongside https://github.com/zkoss/zkcml/pull/1171
=> ZK-5792: fullfill doesn't create all components in a forEach

zkdoc/release-note, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1176
=> ZK-5801: Client MVVM: switching apply template causing javascript error

zkdoc/release-note, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1173
=> ZK-5799: Javascript error when using Pdfviewer in Client MVVM

zkdoc/release-note, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1175
=> ZK-5798: Client MVVM: Content missing in Include

zkdoc/release-note, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1174
=> ZK-5797: Client MVVM Children binding shall ignore null value

zul/src/main/resources/web/js/zul/sel/ItemWidget.ts, zul/src/main/resources/web/js/zul/sel/Listcell.ts, zul/src/main/resources/web/js/zul/sel/Treerow.ts
This PR should be merge alongside zkoss/zkcml#1187
=> refix for B96_ZK_5038Test (refine ZK-5107, ZK-5038)

zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1188
=> ZK-5820: a side effect of ZK-5018 for F95_ZK_4552Test

zkdoc/release-note, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1183
=> ZK-5810: Client MVVM: XEL Methods in include

zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1189
=> ZK-5813: a side effect of ZK-5476 for BookCRUD2Test and BookCRUDTest

zkdoc/release-note
This should be merged alongside https://github.com/zkoss/zkcml/pull/1197.
=> ZK-4962: ZK-3975 regression in mobile

zkdoc/release-note
This should be merged alongside https://github.com/zkoss/zkcml/pull/1201.
=> ZK-5833: ZK-423 regression on Android

zktest/src/main/webapp/test2/F100-ZK-5213.zul, zktest/src/test/java/org/zkoss/zktest/zats/test2/F100_ZK_5213Test.java
This PR should be merged alongside zkoss/zkcml#1218
=> refine ZK-5213: Improve accessibility by add tooltips on icons

zkdoc/release-note
This PR should be merge alongside https://github.com/zkoss/zkcml/pull/1215
=> ZK-5796: Client MVVM shall support resource directory

zul/src/main/resources/web/js/zul/db/datefmt.ts
=> Refine ZK-5615 for ts error

zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/F102_ZK_5642Composer.java, zktest/src/main/webapp/WEB-INF/web.xml, zktest/src/main/webapp/test2/F102-ZK-5642.html, zktest/src/main/webapp/test2/F102-ZK-5642.zul, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1219
=> ZK-5642: zEmbedded support for CometServerPush

zkdoc/release-note, zktest/src/main/webapp/test2/B102-ZK-5616.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5616Test.java
Test cases failed on Jenkins all passed locally.
=> ZK-5616: transparent background in Detail column overlaps non-frozen columns on scroll

zktest/build.gradle
This PR should be merge alongside zkoss/zkcml#1223
=> update zk-webdriver to 1.4.31.0.0

zkdoc/release-note, zktest/src/main/java/org/zkoss/zktest/test2/B102_ZK_5705VM.java, zktest/src/main/webapp/test2/B102-ZK-5705.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5705Test.java
This PR should be merged alongside - https://github.com/zkoss/zkcml/pull/1224
=> ZK-5705: <apply> no longer re-rendering when notifying @load binding

zkdoc/release-note, zktest/src/main/webapp/test2/F102-ZK-4999.zul, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside zkoss/zkcml#1221
=> ZK-4999: searchbox can select the first matched items by default

zktest/build.gradle
Add duplicatesStrategy for war packaging
=> Update zktest build.gradle

release.gradle, zk/src/main/java/org/zkoss/zk/ui/HtmlShadowElement.java, zkdoc/release-note, zktest/src/main/webapp/test2/B100-ZK-5261.zul, zktest/src/test/java/org/zkoss/zktest/zats/test2/B101_ZK_5792Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/F80_ZK_2800Test.java
2. Revert the fix of ZK-5079
This PR should be merged alongside https://github.com/zkoss/zkcml/pull/1231
=> 1. Refix ZK-5261: forEach always re-renders all items

zkdoc/release-note, zktest/src/main/webapp/test2/F102-ZK-5474.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/F102_ZK_5474Test.java, zul/src/main/java/org/zkoss/zul/Decimalbox.java, zul/src/main/java/org/zkoss/zul/Doublebox.java, zul/src/main/java/org/zkoss/zul/Intbox.java, zul/src/main/java/org/zkoss/zul/Longbox.java, zul/src/main/java/org/zkoss/zul/SimpleDoubleSpinnerConstraint.java, zul/src/main/java/org/zkoss/zul/SimpleNumberInputConstraint.java, zul/src/main/java/org/zkoss/zul/SimpleSpinnerConstraint.java, zul/src/main/resources/web/js/zul/inp/Doublespinner.ts, zul/src/main/resources/web/js/zul/inp/NumberInputWidget.ts, zul/src/main/resources/web/js/zul/inp/SimpleNumberInputConstraint.ts, zul/src/main/resources/web/js/zul/inp/Spinner.ts
This PR should be merge alongside zkoss/zkcml#1229.
=> ZK-5474: Provide min and max string constraints for number input elements

zkdoc/release-note, zktest/src/main/webapp/test2/F102-ZK-5597.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/F102_ZK_5597Test.java, zul/src/main/resources/metainfo/xml/zul.xsd
This PR should be merge alongside zkoss/zkcml#1232
=> ZK-5597: vertical stepbar

zkdoc/release-note, zktest/src/main/webapp/test2/B102-ZK-5612.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5612Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4843Test.java, zul/src/main/resources/web/js/zul/inp/ComboWidget.ts, zul/src/main/resources/web/js/zul/inp/Combobox.ts
This should be merged alongside https://github.com/zkoss/zkcml/pull/1235.
=> ZK-5612: combobox popup shows in erratic positions

zkdoc/release-note, zktest/src/main/webapp/test2/B102-ZK-5842.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5842Test.java
The PR should be merged alongside https://github.com/zkoss/zkcml/pull/1243.
=> ZK-5842: a grid with frozen columns has redundant horizontal scrollbar

zktest/src/main/webapp/test2/B102-ZK-5616.zul, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5616Test.java, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5616_1Test.java
The PR should be merged alongside https://github.com/zkoss/zkcml/pull/1244.
=> refix ZK-5616 for mobile devices

zktest/build.gradle
This PR should be merge alongside zkoss/zkcml#1245
=> update zk-webdriver to 1.4.32.0.0

zktest/src/test/java/org/zkoss/zktest/zats/test2/F86_ZK_4235Test.java, zul/src/main/resources/web/js/zul/db/datefmt.ts
=> refine test case ZK-4235

zkdoc/release-note, zktest/src/main/webapp/test2/B102-ZK-5847.zul, zktest/src/main/webapp/test2/config.properties, zktest/src/test/java/org/zkoss/zktest/zats/test2/B102_ZK_5847Test.java, zul/src/main/resources/web/js/zul/grid/Grid.ts, zul/src/main/resources/web/js/zul/mesh/Frozen.ts
The PR should be merged alongside https://github.com/zkoss/zkcml/pull/1247.
=> ZK-5847: frozen columns shift when scrolling a grid on mobile devices

zk/src/main/java/org/zkoss/zk/ui/http/WpdExtendlet.java, zkdoc/release-note, zktest/src/main/webapp/test2/B102-ZK-5747.zul, zktest/src/main/webapp/test2/config.properties
This PR should be merge alongside https://github.com/zkoss/zkcml/pull/1246
=> ZK-5747: Mold default not found in zul.box.Hlayout
