zkoss/zk

- zkdoc/release-note
- zktest/src/archive/test2/B80-ZK-3168.zul
- zktest/src/archive/test2/B80-ZK-3169.zul
- zktest/src/archive/test2/F80-ZK-3098.zul
- zktest/src/archive/test2/config.properties
- zktest/src/org/zkoss/zktest/test2/F80_ZK_3098Composer.java
ZK-3168: Chosenbox doesn't send onSelectSubModel direcly to the server using ListSubModel
ZK-3169: Invalidate on a parent of chosenbox causes selection to disappear using listsubmodel
> ZK-3098: add onItemClick event to Chosenbox

- zk/src/org/zkoss/zk/ui/select/Selectors.java
Hi,
this is a pull regest for http://tracker.zkoss.org/browse/ZK-2582 allowing a priority specification in @Listen() annotations.
Sample:
@Listen("onChange(-100) = #myTextBox")
The intention is to have the @Listen()-Bindings executed after the databinder has finished updated all related objects.
> ZK-2582: Allow specification of Priority for SelectorComposer's @Listen() Annotation

- zhtml/src/org/zkoss/zhtml/impl/AbstractTag.java
Hi,
this is a pull request for http://tracker.zkoss.org/browse/ZK-3097 - It just adds the Serialization-interface to org.zkoss.zhtml.impl.AbstractTag$EncodedURL allowing session serialization.
> ZK-3097: Serialization issue: org.zkoss.zhtml.impl.AbstractTag$EncodedURL is not serializeable

- zk/src/org/zkoss/zk/au/AuRequests.java
- zk/src/org/zkoss/zk/ui/event/MouseEvent.java
Hi,
another small patch: We discovered that the "metaKey" status on OSX - especially in context for a listbox - is handled properly on the javascript side (the meta-key allows multi-select individual entries on OSX like the ctrl key on windows), and also reported properly in the AuRequests data JSON object, but it is simply not mapped to the MouseEvent.
This small pull solves this and the meta key is visible on the MouseEvent.
> MouseEvent: Transport metaKey status

- zkdoc/release-note
- zktest/src/archive/test2/B85-ZK-3707.zul
- zktest/src/archive/test2/B85-ZK-3708.zul
- zktest/src/archive/test2/config.properties
ZK-3708: splitlayout splitter uses inline style makes CSS customization harder
> ZK-3707: splitlayout splitter cursor icon shows only one direction

- zkdoc/release-note
- zktest/src/archive/test2/B85-ZK-3572.zul
- zktest/src/archive/test2/config.properties
- zul/src/org/zkoss/zul/Listbox.java
get value from library property "org.zkoss.zul.listbox.preloadSize" if it exists
and set value to _preloadsz
> ZK-3572: Listbox uses deprecated setPreloadSize instead of library property org.zkoss.zul.listbox.preloadSize

- zk/src/archive/web/js/zk/dom.js
issue: errorbox does not appear in chrome
> refine ZK-2371

- zk/src/archive/web/js/zk/flex.js
Additional margin in new theme caused "hflex does not work properly inside a Toolbar component"
> refine ZK-1706: hflex does not work properly inside a Toolbar component

- build.target.xml
See http://www.oracle.com/technetwork/java/javase/8u121-relnotes-3315208.html
tools/javadoc(tool)
> New --allow-script-in-comments option for javadoc
> The javadoc tool will now reject any occurrences of JavaScript code in the javadoc documentation comments and command-line options, unless the command-line option, --allow-script-in-comments is specified.
> With the --allow-script-in-comments option, the javadoc tool will preserve JavaScript code in documentation comments and command-line options. An error will be given by the javadoc tool if JavaScript code is found and the command-line option is not set.
> JDK-8138725 (not public)
> fixed Javadoc generation fails with jdk1.8.0_121 or later

- zkbind/src/org/zkoss/bind/AnnotateBinder.java
- zkbind/src/org/zkoss/bind/tracker/impl/BindUiLifeCycle.java
- zkdoc/release-note
- zktest/src/archive/test2/B85-ZK-3969-include.zul
- zktest/src/archive/test2/B85-ZK-3969.zul
- zktest/src/archive/test2/config.properties
- zktest/src/org/zkoss/zktest/bind/issue/B01194NestedVMInit.java
- zktest/src/org/zkoss/zktest/test2/B85_ZK_3969VM.java
- zktest/test/java/org/zkoss/zktest/zats/test2/B85_ZK_3969Test.java
Notice: it breaks ZK-3871 (Have told to Klyve)
Before merging, merge https://github.com/zkoss/zk/pull/1179 first!
> ZK-3969: MVVM viewmodel name bleed into include / other idspace

- zkdoc/release-note
- zul/src/archive/metainfo/xml/zul.xsd
ZK-4348: zul XSD declares the attribute "badgeText" in wrong case
ZK-4350: zul XSD doesn't declare onCreate for charts
ZK-4356: missing "text" attribute on timebox in zul XSD
> ZK-4345: XSD doesn't define hflex and vflex for charts

- zktest/pom.xml
- zktest/test/java/org/zkoss/zktest/zats/ChromiumHeadlessDriver.java
- zktest/test/java/org/zkoss/zktest/zats/WebDriverTestCase.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F50_2940704_GridTest.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F50_2940704_ListboxTest.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F50_2940704_TreeTest.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F50_3052761Test.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F86_ZK_4059Test.java
Upgrade to webdrivermanager 3.6.2
Fixed eval() returning nothing causes JavaScript circular exception
Add verbose log for debugging (/tmp/chromedriver.log)
> Upgrade to Chromium 77.0.3835.0 (8.6 branch)

- zk/src/archive/web/js/zk/au.js
1. rename parameter to be more readable
2. remove setTimeout to wait ZK
3. set xhrWithCredentials flag in ZK (instead of setting in desktop)
> refine ZK-4507

- zktest/src/archive/wcag/menubar.zul
- zul/src/archive/web/js/zul/menu/Menu.js
- zul/src/archive/web/js/zul/menu/Menubar.js
- zul/src/archive/web/js/zul/menu/Menuitem.js
- zul/src/archive/web/js/zul/menu/Menupopup.js
Open Next Menupopup, move focus
Regain focus to the root menu while the menuitem is activated
Press space to open menupopup
Open menupopup, focus on the first menuitem
> refine ZK-4598: Menubar arrow keys navigation

- zktest/src/archive/test2/B95-ZK-4453.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4453Test.java
- zul/src/archive/web/js/zul/inp/InputWidget.js
Not actually fix it, but extracting a method for easier modification.
> ZK-4453: onError fires again when valid value is entered

- zul/src/archive/web/js/zul/wgt/less/toolbar.less
it causes the content height not expandable
> revert ZK-4560: toolbarbutton apply min-height workaround

- zkdoc/release-note
- zktest/src/archive/test2/B95-ZK-4729.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4729Test.java
- zul/src/archive/web/js/zul/inp/Errorbox.js
ZK-4729: z-errorbox disappears after clicking
> ZK-4729: z-errorbox disappears after clicking

- zkdoc/release-note
- zktest/src/archive/test2/B95-ZK-4766.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B95_ZK_4766Test.java
ZK-4767: splitter aria-controls wrong for collapse="after"
ZK-4768: splitlayout aria-controls wrong for collapse="after"
ZK-4769: splitter aria-valuenow reversed for collapse="after"
ZK-4770: splitlayout aria-valuenow reversed collapse="after"
> ZK-4766: splitter aria-valuenow /-valuetext don't update on collapse

- zul/src/archive/web/js/zul/dom.js
- zul/src/archive/web/js/zul/wnd/less/window.less
refine ZK-4760: default error message box hard coded width (too small)
> refine ZK-4760: default error message box hard coded width (too small)

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-4762.zul
- zktest/src/archive/test2/config.properties
- zul/src/archive/web/js/zul/mesh/Frozen.js
ZK-4762: listbox with frozen columns cannot show all headers under non-100% zoom level(non-smooth)
> ZK-4762: listbox with frozen columns cannot show all headers under non-100% zoom level(non-smooth)

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-4701.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4701Test.java
ZK-4701: chosenbox initial width too short to display emptyMessage
> ZK-4701: chosenbox initial width too short to display emptyMessage

- zkdoc/release-note
- zul/src/org/zkoss/zul/Menubar.java
ZK-4811: menubar autodrop="false" has no effect on nested submenus
> ZK-4811: menubar autodrop="false" has no effect on nested submenus

- zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4330Test.java
- zul/src/archive/web/js/zul/sel/Treecol.js
refine ZK-4330 nested tree item checkmark disappears automatically
> refine ZK-4330 nested tree item checkmark disappears automatically

- zkdoc/release-note
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4793Test.java
- zul/src/org/zkoss/zul/Tree.java
ZK-4793: IndexOutOfBoundsException Tree.renderItemByPath
> ZK-4793: IndexOutOfBoundsException Tree.renderItemByPath

- zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4783Test.java
- zul/src/archive/web/js/zul/wnd/less/window.less
- zul/src/archive/web/zul/less/_zkvariables.less
- zul/src/archive/web/zul/less/profiles/_compact.less
refine ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)
> refine ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)

- zktest/src/archive/test2/F96-ZK-4783.zul
- zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4783Test.java
- zul/src/archive/web/js/zul/wnd/messagebox.js
refine ZK-4783: Modify error message box CSS design (provide scrollbar while word-break fail)
> refine ZK-4783 zul

- zk/src/archive/web/js/zk/dom.ts
- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-4831.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_4831Test.java
ZK-4831: parseStyle splits css string incorrectly
> ZK-4831: parseStyle splits css string incorrectly

- zkdoc/release-note
- zul/src/archive/web/js/zul/inp/less/slider.less
ZK-4858: slider knob styles contain invalid css property
> ZK-4858: slider knob styles contain invalid css property

- zktest/src/archive/test2/B70-ZK-2567.jsp
- zktest/test/java/org/zkoss/zktest/zats/test2/B80_ZK_2964Test.java
- zktest/test/java/org/zkoss/zktest/zats/test2/B80_ZK_3046Test.java
- zktest/test/java/org/zkoss/zktest/zats/test2/B85_ZK_3848Test.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4745Test.java
- zktest/test/java/org/zkoss/zktest/zats/test2/F96_ZK_4745_2Test.java
2567: conflict with ZK-2642
2964: Update Time Parser
3046: Remove the count check (it depends on Java versions)
3848: PowerMock Java 11 workaround
4745: Format differs in Java versions
> refine test cases

- zul/src/archive/web/js/zul/inp/Bandpopup.js
refine ZK-4748: bandpopup close while open the treeitem in No-A11y
> refine ZK-4748: bandpopup close while open the treeitem in No-A11y

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-4995.zul
- zktest/src/archive/test2/config.properties
ZK-4995: signature component on tablet/mobile cutting off image
> ZK-4995: signature component on tablet/mobile cutting off image

- zkdoc/release-note
ZK-4997: button with autodisable doesn't trigger popup
> ZK-4997: button with autodisable doesn't trigger popup

- zk/src/org/zkoss/zk/ui/http/Utils.java
- zk/src/org/zkoss/zk/ui/http/WebManager.java
- zk/src/org/zkoss/zk/ui/http/WpdExtendlet.java
- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-4986.zul
- zktest/src/archive/test2/config.properties
ZK-5071: org.zkoss.zk.ui.versionInfo.enabled cannot bust browser cache
> ZK-4986: version information not salted for static resources

- zkdoc/release-note
- zktest/src/main/webapp/test2/B100-ZK-5145.zul
- zktest/src/main/webapp/test2/config.properties
- zktest/src/test/java/org/zkoss/zktest/zats/test2/B100_ZK_5145Test.java
ZK-5145: Chosenbox smart update emptyMessage doesn't work
> ZK-5145: Chosenbox smart update emptyMessage doesn't work

- zkdoc/release-note
- zktest/src/main/webapp/test2/B100-ZK-5123.zul
- zktest/src/main/webapp/test2/config.properties
- zktest/src/test/java/org/zkoss/zktest/zats/test2/B100_ZK_5123Test.java
ZK-5123: Searchbox open attribute doesn't work while initializing
> ZK-5123: Searchbox open attribute doesn't work while initializing

- zk/src/org/zkoss/zk/ui/event/ClientInfoEvent.java
Added more information to the @deprectated field of the javadoc, following customer feedback that the reason to deprecate was unclear
> ClientInfoEvent deprecated javadoc additional info

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5170.zul
- zktest/src/archive/test2/config.properties
This should be merged alongside [PR#236](https://github.com/zkoss/zkthemes/pull/236) in zkthemes
> ZK-5170: borderlayout title css rules are missing under sapphire theme

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5253.zul
- zktest/src/archive/test2/config.properties
This PR should be merge alongside https://github.com/zkoss/atlantic/pull/226
> ZK-5253: title of borderlayout north/south shouldn't rotate 90 degrees

- zephyr-test/src/main/java/org/zkoss/clientbind/test/issue/B01194NestedVMInit.java
- zul/src/main/resources/web/js/zul/inp/Combobox.ts
PR should be committed alongside https://github.com/zkoss/zkcml/pull/982
> ZK-5275: Client MVVM: Support widget properties in command expression

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5260.zul
- zktest/src/archive/test2/config.properties
- zktest/src/org/zkoss/zktest/test2/B96_ZK_5260VM.java
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5260Test.java
This PR should be merged alongside [ZKCML#989](https://github.com/zkoss/zkcml/pull/989).
> ZK-5260: chosenbox options don't escape HTML characters 

- zul/src/archive/web/js/zul/sel/SelectWidget.js
- zul/src/org/zkoss/zul/Listbox.java
`data.get("firstItemIndex")` or `data.get("lastItemIndex")` could be `null`. In that case, use the available values from `_items`.
> Fix NPE in B70_ZK_2534Test#testSelectRange due to B96-ZK-2658

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5434.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5434Test.java
The UTC offset should be -6 for America/Mexico_City.
> ZK-5434: Datebox show different time when running with -Duser.timezone="America/Mexico_City"

- @types/zk/zk.d.ts
- zk/src/archive/web/js/zk/widget.ts
- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5368.zul
- zktest/src/archive/test2/config.properties
- zktest/src/org/zkoss/zktest/test2/B96_ZK_5368VM.java
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5368Test.java
This PR should be merged alongside [ZK#995](https://github.com/zkoss/zkcml/pull/995).
> ZK-5368: Tree with client-ROD fails to replace treerow if parent is currently not rendered

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5258.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5258Test.java
This PR builds on [ZK#2944](https://github.com/zkoss/zk/pull/2944). Please merge that first.
> ZK-5258: setFocus() doesn't work on a textbox in a modal window

- zkdoc/release-note
- zktest/src/archive/test2/B96-ZK-5414.zul
- zktest/src/archive/test2/config.properties
- zktest/test/java/org/zkoss/zktest/zats/test2/B96_ZK_5414Test.java
This PR should be merge alongside [zkcml#998](https://github.com/zkoss/zkcml/pull/998).
> ZK-5414: onTimer event causes a cascader to close its next level items

- zktest/src/org/zkoss/zktest/test2/B96_ZK_5260VM.java
This PR shoudl be merged alongside [zkcml#1002](https://github.com/zkoss/zkcml/pull/1002).
Unconditionally escaping strings in ZK-5260 conflicts with the documentation for ItemRenderer::render and ZK-2691.
`model.add("4@email.io <aerror");` should be allowed because "`ItemRenderer::render` renders the data to the corresponding HTML fragment, and returns the HTML `fragment.model." See https://www.zkoss.org/javadoc/latest/zk/org/zkoss/zul/ItemRenderer.html
> Revert ZK-5260.

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1008.
> ZK-5373: focus button, z-focus-a, doesn't have an accessible name

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1011.
> ZK-5462: empty listbox fails to pass lighthouse accessibility check for missing required role

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1012.
> ZK-5479: checkboxes in a listheader have missing required aria attribute: aria-checked 

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1017.
> ZK-5492: The elements with an id of 'tpad-tbl' and 'bpad-tbl' do not have the correct role

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1016.
> ZK-5491: Multislider and Rangeslider's [aria-*] attributes do not match their roles

- zkdoc/release-note
This PR should be merged alongside https://github.com/zkoss/zkcml/pull/1038
> ZK-5450: 2 NEXT_SIBLING for targetId don't pass the expected value

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1015.
> ZK-5490: Grid's [aria-*] attributes do not match their roles

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1046.
> ZK-5525: Checkbox tristate [aria-checked] attribute missing "mixed" state

- zkdoc/release-note
This should be merged alongside zkoss/atlantic#234 and zkoss/zkthemes#245.
> ZK-5592: Deprecate the ancient themes (Breeze, Sapphire, Silvertail, and Atlantic) in ZK 10

- zktest/build.gradle
- zktest/src/test/java/org/zkoss/zktest/zats/test2/B100_ZK_5650Test.java
This should be merged after https://github.com/zkoss/zats/pull/37 to use the latest version of zats-mimic-ext.
This should be merged alongside https://github.com/zkoss/zkcml/pull/1139.
> Refine B100_ZK_5650Test

- zktest/build.gradle
- zktest/gradle.properties
This PR should be merge alongside zkoss/zkcml#1148.
> Jacoco coverage report

- zkdoc/release-note
- zktest/src/main/webapp/test2/config.properties
This should be merged alongside https://github.com/zkoss/zkcml/pull/1165
> ZK-5659: Tree only renders 50 nodes in client mvvm

- zk/src/main/resources/web/js/zk/crashmsg.ts
- zk/src/main/resources/web/js/zk/zk.ts
- zkdoc/release-note
- zktest/src/main/java/org/zkoss/zktest/util/ZkCspFilterStrictDynamic.java
- zktest/src/main/webapp/test2/B101-ZK-5716-web.xml
- zktest/src/main/webapp/test2/B101-ZK-5716.zul
- zktest/src/main/webapp/test2/config.properties
- zktest/src/test/java/org/zkoss/zktest/zats/test2/B101_ZK_5716Test.java
- zul/src/main/resources/web/js/zul/db/mold/calendar.js
- zul/src/main/resources/web/js/zul/menu/mold/menupopup.js
- zul/src/main/resources/web/js/zul/mesh/HeaderWidget.ts
- zul/src/main/resources/web/js/zul/sel/mold/listbox.js
- zul/src/main/resources/web/js/zul/sel/mold/tree.js
- zul/src/main/resources/web/js/zul/wnd/Window.ts
This should be merged alongside https://github.com/zkoss/zkcml/pull/1168
> ZK-5716: Errorbox contains inline script

- zkdoc/release-note
- zktest/src/main/webapp/test2/B101-ZK-5787.zul
- zktest/src/main/webapp/test2/config.properties
- zktest/src/test/java/org/zkoss/zktest/zats/test2/B101_ZK_5787Test.java
This should be merged alongside https://github.com/zkoss/zkcml/pull/1169
> ZK-5787: aria-hidden elements do not contain focusable elements

- babel-plugin-expose-private-functions-and-variables.js
- zkdoc/release-note
- zktest/src/main/webapp/test2/B101-ZK-5802.zul
- zktest/src/main/webapp/test2/config.properties
- zktest/src/test/java/org/zkoss/zktest/zats/test2/B101_ZK_5802Test.java
This PR should be merge alongside zkoss/zkcml#1180.
> ZK-5802: _listenFlex, _unlistenFlex declared on static member _ are used directly, cannot be overriden

- zk/src/main/java/org/zkoss/zk/ui/http/ZKWebSocket.java
- zkdoc/release-note
This should be merged alongside https://github.com/zkoss/zkcml/pull/1194
> ZK-5561: ZK Websocket Quarkus compatibility

- zkdoc/release-note
- zktest/build.gradle
- zktest/src/main/webapp/test2/B102-ZK-4337.zul
- zktest/src/main/webapp/test2/B102-ZK-5230-1.zul
- zktest/src/main/webapp/test2/B102-ZK-5230.zul
- zktest/src/main/webapp/test2/B102-ZK-5231.zul
- zktest/src/main/webapp/test2/B102-ZK-5898.zul
- zktest/src/main/webapp/test2/B86-ZK-4095.zul
- zktest/src/main/webapp/test2/config.properties
ZK-5231: removing a barcodescanner immediately right after the browser renders it causes javascript error
ZK-5898: QR code scanning does not work in Barcodescanner
This PR should be merge alongside zkoss/zkcml#1212
> ZK-5230: adding Barcodescanner twice causes javascript errors

- zkdoc/release-note
- zktest/src/main/webapp/test2/B102-ZK-4861.zul
- zktest/src/main/webapp/test2/config.properties
- zul/src/main/resources/web/js/zul/db/Timebox.ts
This PR should be merged alongside https://github.com/zkoss/ztltest/pull/401
> ZK-4861: Inconsistent input options in Android, cause unreliable timebox input

- zkdoc/release-note
This PR should be merge alongside zkoss/zkcml#1248
> ZK-5674: i11n labels does not load in a shadow element in client-mvvm
